<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:workflow xmlns:ns2="http://vmware.com/vco/workflow" root-name="item2" object-name="workflow:name=generic" id="7a2d6065-8f72-4e0c-9234-8b31e9757f1c" editor-version="2.0" version="0.0.0" api-version="6.0.0" allowed-operations="vef" restartMode="1" resumeFromFailedMode="0">
    <display-name>Workflow That is Using Throw Exception</display-name>
    <description>This workflow uses a throw exception when needed</description>
    <position y="65.0" x="50.0"/>
    <input>
        <param name="throwException" type="boolean">
            <description>Do you want to throw an exception?</description>
        </param>
    </input>
    <output/>
    <attrib name="errorCode" type="string">
        <value encoded="n">This is our exception message</value>
        <description>Message thrown by exception</description>
    </attrib>
    <workflow-item name="item0" throw-bind-name="errorCode" type="end" end-mode="1" comparator="0">
        <in-binding/>
        <out-binding/>
        <position y="65.0" x="300.0"/>
    </workflow-item>
    <workflow-item name="item1" type="end" end-mode="0" comparator="0">
        <in-binding/>
        <out-binding/>
        <position y="130.0" x="180.0"/>
    </workflow-item>
    <workflow-item name="item2" out-name="item0" alt-out-name="item1" type="condition" comparator="0">
        <display-name>Throw Exception?</display-name>
        <script encoded="false">// Generated by the system, cannot be edited
return (throwException === true);</script>
        <in-binding>
            <bind name="throwException" type="boolean" export-name="throwException"/>
        </in-binding>
        <out-binding/>
        <description>Custom decision based on a custom script.</description>
        <condition name="throwException" type="boolean" comparator="0" label="null"></condition>
        <position y="65.0" x="140.0"/>
    </workflow-item>
    <presentation/>
</ns2:workflow>
